fossasia/2018.fossasia.org

index.html

Loads tweets & external JS via HTTPS
@mariobehling Please review
Demo: https://geekyd.github.io/2018.fossasia.org/

Loads tweets & external JS via HTTPS

---

index.html

Reverts fossasia/2018.fossasia.org#32
Sorry, I can not see the tweets loading here:
https://2018.fossasia.org/

Revert "Loads tweets & external JS via HTTPS"

---

index.html

Change text color of the link which was invisible.

Fix issue #31. Change color of the link.

---

css/custom.css

Color of the link/text on the
button changed to white to make
it visible.
Closes https://github.com/fossasia/2018.fossasia.org/issues/31

Change color of text on button:

---

css/theme.css
index.html

Zoom button fix

---

img/README.md

This adds a note so that future images have a guideline.
fix #30

fix #30 - note for speaker images

---

css/theme-lava.css

@niccokunzmann 
please preview the changes and review the PR..
link :
http://www.ashishkrgoyal.me/2018.fossasia.org/
Thanks 👍

Zooming in moves menu bar #47_fixes

---

css/theme-lava.css

Fixes #49 
@niccokunzmann @mariobehling

Prevent hover overflow

---

index.html

Only make map zoomable after initial click on area

BUG #54 Fix

---

404.html

@mariobehling The buttons on 404.html do not function. 'Take me home' button redirects to index.html. 'Report' takes the user to github repository for creating an issue.

Fix the buttons on 404.html

---

index.html

This PR fixes issue of no tweets in index.html

Fixes #29: Load tweets on index.html

---

css/custom.css

Fixed links is not showing in Social Event program

---

index.html

Add Joerg Henning to the team page

---

index.html

Fixes #94 
-sidebar menu text changed
-menu reordered because schedule comes before topics in the main content.
Live preview : `updating... hang on`

link text changed

---

index.html

Please review and provide feedback. I will make necessary changes if required.
Here is the <a href = "https://achiv.github.io/">Preview</a>
I am also attaching the screenshot

Added Philip Paeps to the organisation team #100

---

css/theme-lava.css
index.html

Issue Addressed #101 
Please provide feedback
Here is the <a href = "https://achiv.github.io">Preview</a>
I am also attaching the screenshot

Added "Join us at the ...." and social media sharing icons

---

css/custom.css
index.html

Fixes #107 
Before
After
changes can be previewed at https://himanish-star.github.io/2018.fossasia.org/

updated bio data of Felipe Hoffa #107

---

css/custom.css
index.html

* Updated Speaker's Bio of Felipe Hoffa
* Properly aligned
* Fixes #107 
**Preview Link :** https://duttaditya18.github.io/2018.fossasia.org/

Updated Speaker's Bio - Felipe Hoffa

---

index.html

Added Carsten Haitzler as featured speaker and moved Takasu Masakazu to general speakers       

---

index.html

Fixed alternate text

---

css/custom.css

Fixes part of #84 
@mariobehling

changed color of links in social events program

---

index.html

Fixes #120 :Fixed bugged icon link and Added more icons

---

index.html

Fixes #127. Event Partner Social profiles

---

index.html

#123 I've solved this issue :D

Added missing links

---

index.html

Fixes #147
https://arjunpandey2003.github.io/2018.fossasiaplanc.org/

Removed speakers

---

index.html

* **_Added @fossasia company link, as it was commented in the codebase :wink:_** 
- _In the head_
- _In the body_
Added Details : 
- **arynchoong**
- **robertbobreyes**
- **libedinskylab**
**_Preview link - https://0x48piraj.github.io/2018.fossasia.org_**
Ping @mariobehling :+1:

Fixes #134 : Added FOSSAIA's Company LinkedIn link, Added missing social links 

---

index.html

Fixes: #153 
@hpdang Please review.
Review Link: https://simsausaurabh.github.io/2018.fossasia.org/

Fixed #153: 'Update bio of speakers under featured speaker section'

---

index.html

Fixes: #164 
Deployment link: https://simsausaurabh.github.io/2018.fossasia.org/
After Changes: single linkedIn link

Fixed #164: 'Repeated same linkedIn link for fossasia in Event Partners'

---

edit.html
index.html

Added 8 Speakers. 
<a href="https://achiv.github.io/2018.fossasia.org/">Preview link</a>

Fixed #175

---

index.html

fixes #190 
preview : https://nityanandagohain.github.io/2018.fossasianitya.io/

speaker's company name updated

---

index.html

Update job title
<a href="https://achiv.github.io/2018.fossasia.org/">Preview</a>

Fixed #194

---

index.html

Added the Job Title

---

index.html

Removed the Speaker

---

index.html

Added the Job title- Andre

---

index.html

Added Job title - William Tan

---

index.html

Added Job Title - Khalil

---

index.html

Updated Job title

---

index.html

Correct alt #217

---

index.html

Added Job title- Nan Xiao

---

index.html

Fixes #193 #195  #198 #201 . @hpdang

Added Missing Job titles

---

index.html

Done! with reference to #234 . @hpdang

Fixed the Job title #234

---

index.html

Swapped the Position Keya and Preetam

---

index.html

Fixes: #228 
@hpdang Please review
Preview link: https://simsausaurabh.github.io/2018.fossasia.org/

Fixed #228: 'Swap Speakers' Postions: Oskari Saarenmaa >< Mete Atamel'

---

css/theme-lava.css
index.html

Now when we want to zoom in and out on the map clicking on the map activate the zooming functionality and the zoom buttons are also activated.
fixes #245 
fixes #54 
preview https://nityanandagohain.github.io/2018.fossasianitya.io/

Map can be zommed after clicking on it.

---

index.html

Fixes #274 
Also, make the coding pattern uniform
**Preview link** : https://akshatnitd.github.io/2018.fossasia.org/
Made changes to the code indentation in the `index.html` file to improve code quality.

Fixes #274 : Correct indentation

---

index.html

Corrected error in speaker name :Tiejun Chen

---

index.html

Changed title for Christopher Skene.
Fixes: #386 
Link: https://ritikamotwani.github.io/2018.fossasia.org/

Change title for Christopher Skene

---

index.html

Fixes #390 
Preview: https://rishabh19038.github.io/2018.fossasia.org/
Made following changes:
Kamesh Sampath
Director of Developer Experience
Red Hat India
Suraj Narwade
Associate Software Engineer
Red Hat
Harin Nalin Vadodaria
Principal MTS
Oracle

Added Speaker Titles

---

index.html

Removed Duplicate- Divyam Madaan

---

index.html

Fixes #437 
Preview: https://rishabh19038.github.io/2018.fossasia.org/

Fixes #437

---

index.html

Modifies the title of the speaker.
Fixes: #440 
Link: https://ritikamotwani.github.io/2018.fossasia.org/

Modify title for speaker Philip Paeps

---

index.html

Fixes #442 
Preview: https://rishabh19038.github.io/2018.fossasia.org/

Update Profile of Speaker Calvin Cheng

---

404.html
500.html

Fixes: #456
fixed "take me home button" on error pages(404.html and 500.html) see links:
page 404.html
current behaviour : https://2018.fossasia.org/404.html
expected behaviour : https://prshntsingh.github.io/2018.fossasia.org/404.html
page 500.html
current behaviour : https://2018.fossasia.org/500.html
expected behaviour : https://prshntsingh.github.io/2018.fossasia.org/500.html
@hpdang  @mariobehling please review

fixed "take me home" button

---

index.html
js/tweetsfetcher.js

Fixes: #174 
Preview Link: https://simsausaurabh.github.io/2018.fossasia.org/
@mariobehling @hpdang please review.

Fixed #174: 'Only show tweets and retweets of @fossasia '

---

css/theme-lava.css
index.html

Fixes: #500 
Added additional style to increase size of logos we want.
Deployment link: https://simsausaurabh.github.io/2018.fossasia.org/
@mariobehling please review.

Fixed #500: Increase size of logos - offer additional style

---

exhibition/index.html

Fixed #512 
The color of the Scroll over links are the same in the website so they weren't changed.
Preview: https://flaredragon.github.io/2018.fossasia.org/exhibition/index.html

Fixes #512 :Moved exhibition.html to /exhibition/index.html and fixed color issues 

---

index.html

Fixes #505
fixed  errors in speakers' links.
preview link : https://prshntsingh.github.io/2018.fossasia.org/
@mariobehling @hpdang

fixed errors in speakers' links

---

exhibition/index.html

Add Exhibitors Info

---

css/custom.css

Issue with speakers alignment for smaller browser size solved

---

index.html

Preview: http://naokichau.github.io/2018.fossasia.org
Resolved #540 & #541

Resolved #540 & #541

---

exhibition/index.html

Fixes #520 .
@hpdang please review.
Test link : https://rawgit.com/PrP-11/2018.fossasia.org/b1/exhibition/

Add links for exhibition page

---

exhibition/index.html

To fix: #546: Exhibitors on the exhibition page (Continue from #520)
Preview: https://mengjiann.github.io/2018.fossasia.org/exhibition/index.html

Fix for #546: Exhibitors on the exhibition page (Continue from #520)

---

index.html

Also changed job title to reflect current status.
Closes: #560

Add bio of Balasankar C

---

index.html

Fixes #555 
@kathyho31
Test Link:
https://rawgit.com/PrP-11/2018.fossasia.org/b2/index.html

Update FOSSASIA Team's info

---

css/custom.css

Fixes #552 
Test link : https://rawgit.com/PrP-11/2018.fossasia.org/b1/index.html
before:
After:

make tweetbox responsive

---

index.html
js/scripts.js

Resolves #554 
Let me know if further changes are to be made.

Honeypot feature added

---

index.html

Fixes: #565
Swapped speakers' positions: Loi Luu & Ramji Venkateswaran
Deployment link: https://prshntsingh.github.io/2018.fossasia.org/

Swapped speakers

---

exhibition/index.html

Fixes: #580 
Added "FOSSASIA Swag and Membership" table and description.
Deployment link: https://prshntsingh.github.io/2018.fossasia.org/exhibition/index.html

Added "FOSSASIA Swag and Membership" table and description

---

index.html

Fixes: #588
resized google cloud logo
Deployment link: https://prshntsingh.github.io/2018.fossasia.org/

resized google cloud logo

---

exhibition/index.html

To fix #610: Update the autodesk description.
Preview: https://mengjiann.github.io/2018.fossasia.org/exhibition/index.html#exhibitors

To fix #610: Update the autodesk description.

---

index.html

Fix #600 Updating Adarsh S info.

---

index.html

Added some spacing between buttons and between a button and a image for mobile view ,basically to be responsive.

Margin between buttons and picture

---

css/custom.css
index.html

I have added the required margin between the social media icons so that they look good in small screens. Thus in small screens it will like
@mariobehling  @akshatnitd @simsausaurabh please look into this!!! I hope this will bring the required change in all screen sizes. This is my first pull request in FOSSASIA. Hope my journey in FOSSASIA stays happy and exciting!!

added margin between social media icons in small screens
